### ISSUE TITLE
need final html pages

### ISSUE THREAD

**Issue by RashinShan** [RashinShan/hey-app#2]
for creating backend we backend team needs to get final front end html files @RDCVithana  @Jaanulittleluv

**Comment by Jaanulittleluv** [comment]
@RDCVithana :(

**Comment by Jaanulittleluv** [comment]
@RashinShan look it in front end branch

**Comment by RashinShan** [comment]
ok @Jaanulittleluv

**Comment by rdcvithana** [comment]
Now ok,all pages are completed.
