### ISSUE TITLE
front end form not compleate

### ISSUE THREAD

**Issue by RashinShan** [RashinShan/hey-app#4]
in front end some forms have not complaeted ways with out action or without type of buttons so please check it @RDCVithana  @Jaanulittleluv

**Comment by RashinShan** [comment]
and also registration page you need to make update field for images users needs to upload profile picture @RDCVithana  @Jaanulittleluv

**Comment by RashinShan** [comment]
done

**Comment by Jaanulittleluv** [comment]
did all the works are completed? what about front end form? @RashinShan
